#pragma once

#include "components/CircleShape.hpp"
#include "components/ConvexShape.hpp"
#include "components/Position.hpp"
#include "components/RectangleShape.hpp"
#include "components/Rotation.hpp"
#include "components/Scale.hpp"
#include "components/SceneInfo.hpp"
#include "components/Camera.hpp"
#include "components/RigidBody.hpp"
#include "components/Tag.hpp"
#include "components/CompoundSprite.hpp"
#include "components/Sprite.hpp"
#include "components/PolygonShape.hpp"